# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dumptruckd < Formula
  desc "A modular database backup daemon"
  homepage "https://github.com/Saadlulu/dumptruckd"
  version "0.3.0"
  license "MIT"

  depends_on "mysql-client" => :optional
  depends_on "postgresql" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.3.0/dumptruckd_0.3.0_darwin_amd64.tar.gz"
      sha256 "7f98a715ad6e0393f09a1006cb711d669330d1ccfa7f9d9933cd70829fadeb8b"

      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.3.0/dumptruckd_0.3.0_darwin_arm64.tar.gz"
      sha256 "b49bc08ec394c602303da4c10fb9d6fe78daaf2d83ec9195632916dc8bf05118"

      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.3.0/dumptruckd_0.3.0_linux_amd64.tar.gz"
      sha256 "2c919d531e54088c8eb26fc01631a8ff3e4af1db0045275bc6f59e7365a78599"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.3.0/dumptruckd_0.3.0_linux_armv6.tar.gz"
      sha256 "eebb432e9ca82810757ac6df4b33d8433e2ce0405d7aec67dec0ebb4d0d70052"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.3.0/dumptruckd_0.3.0_linux_arm64.tar.gz"
      sha256 "940e87c369caeabacc6114c73c7927d5b05e9ee0f342e06e5657a92e376f94be"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
  end

  def post_install
    (var/"backups/dumptruckd").mkpath
    (var/"log").mkpath
  end

  service do
    run [opt_bin/"dumptruckd", "-config", etc/"dumptruckd/dumptruckd.toml"]
    keep_alive true
    log_path var/"log/dumptruckd.log"
    error_log_path var/"log/dumptruckd.log"
  end

  test do
    system "#{bin}/dumptruckd", "-version"
  end
end
