# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dumptruckd < Formula
  desc "A modular database backup daemon"
  homepage "https://github.com/Saadlulu/dumptruckd"
  version "0.2.0"
  license "MIT"

  depends_on "mysql-client" => :optional
  depends_on "postgresql" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.0/dumptruckd_0.2.0_darwin_amd64.tar.gz"
      sha256 "fa490cca0b9f0cb8a219f0c545bb3cd45ff3f04db63d5d8670056fffc5c82794"

      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.0/dumptruckd_0.2.0_darwin_arm64.tar.gz"
      sha256 "16fe813f90cdb113a7b420233f687fcdb8cac087996c8bea09486c9b8c4f086b"

      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.0/dumptruckd_0.2.0_linux_amd64.tar.gz"
      sha256 "30602497d5d260090ca244876a2f51a05094b08fcd828462c02199a948e5986f"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.0/dumptruckd_0.2.0_linux_armv6.tar.gz"
      sha256 "1cc07c06593ea6ae924ce6694402539c7548a8954fb1cfef0e142562e7731cbe"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.0/dumptruckd_0.2.0_linux_arm64.tar.gz"
      sha256 "060f82e95dd62d9919949e37b306ad798c0246c9f278a3842b6baf1de92065a7"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
  end

  def post_install
    (var/"backups/dumptruckd").mkpath
    (var/"log").mkpath
  end

  service do
    run [opt_bin/"dumptruckd", "-config", etc/"dumptruckd/dumptruckd.toml"]
    keep_alive true
    log_path var/"log/dumptruckd.log"
    error_log_path var/"log/dumptruckd.log"
  end

  test do
    system "#{bin}/dumptruckd", "-version"
  end
end
