# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dumptruckd < Formula
  desc "A modular database backup daemon"
  homepage "https://github.com/Saadlulu/dumptruckd"
  version "0.2.1"
  license "MIT"

  depends_on "mysql-client" => :optional
  depends_on "postgresql" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.1/dumptruckd_0.2.1_darwin_amd64.tar.gz"
      sha256 "6471f4bed058a2be951ff2678ee5812527d43a857854c19631ad439cbdb34e4d"

      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.1/dumptruckd_0.2.1_darwin_arm64.tar.gz"
      sha256 "e618f240a3ecd917ae2fbbedf51ba63e57a95de95abb38405d6c304abbba7d22"

      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.1/dumptruckd_0.2.1_linux_amd64.tar.gz"
      sha256 "ee23f911e88bca405e7df6d5f62a3926b8416eb0c4a0d19e970645fa8b5c1ffa"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.1/dumptruckd_0.2.1_linux_armv6.tar.gz"
      sha256 "c308ad098a6e1f149a4048c5ad5c28b3a377cf95410850e57fc53e82e895fb62"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Saadlulu/dumptruckd/releases/download/v0.2.1/dumptruckd_0.2.1_linux_arm64.tar.gz"
      sha256 "7043b04777f8520c4181b03d92869d6d8fcdad835a0bbd058e32521a97ac7e7d"
      define_method(:install) do
        bin.install "dumptruckd"
        (etc/"dumptruckd").mkpath
        (etc/"dumptruckd").install "config/dumptruckd.toml.example"
        (etc/"dumptruckd").install "config/example-single-file.toml"
        (etc/"dumptruckd").install "examples/dumptruckd.service"
      end
    end
  end

  def post_install
    (var/"backups/dumptruckd").mkpath
    (var/"log").mkpath
  end

  service do
    run [opt_bin/"dumptruckd", "-config", etc/"dumptruckd/dumptruckd.toml"]
    keep_alive true
    log_path var/"log/dumptruckd.log"
    error_log_path var/"log/dumptruckd.log"
  end

  test do
    system "#{bin}/dumptruckd", "-version"
  end
end
